import os
import sys
# Dynamically add project root to python path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import gradio as gr
import torch
from PIL import Image
import numpy as np
from transformers import AutoTokenizer

from src.data.augmentations import get_transforms
from src.models.multimodal import MultimodalMedicalReportGenerator

# Configuration & Global State
DEFAULT_CHECKPOINT = "models/checkpoints/vlm_stage2_best.pt"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = None
tokenizer = None
current_checkpoint = None

def load_vlm_model(checkpoint_path):
    """
    Thread-safe model loader for Gradio session.
    """
    global model, tokenizer, current_checkpoint
    
    if not os.path.exists(checkpoint_path):
        return f"Error: Checkpoint file not found at {checkpoint_path}. Please train the model or place weights in the models directory first."
        
    try:
        print(f"Loading checkpoint weights: {checkpoint_path}")
        checkpoint_data = torch.load(checkpoint_path, map_location="cpu")
        ckpt_args = checkpoint_data["args"]
        
        # Load corresponding tokenizer
        lang_model = ckpt_args["language_model"]
        tokenizer = AutoTokenizer.from_pretrained(lang_model)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token
            
        # Reconstruct VLM Architecture
        model = MultimodalMedicalReportGenerator(
            vision_model=ckpt_args["vision_model"],
            language_model=ckpt_args["language_model"],
            projector_type=ckpt_args["projector_type"],
            freeze_vision=True,
            use_lora=(checkpoint_data.get("stage", 1) == 2),
            lora_r=ckpt_args.get("lora_r", 8)
        )
        
        model.load_state_dict(checkpoint_data["model_state_dict"])
        model = model.to(device)
        model.eval()
        
        current_checkpoint = checkpoint_path
        return f"Successfully loaded checkpoint: {os.path.basename(checkpoint_path)} on {device}"
    except Exception as e:
        return f"Failed to load checkpoint: {str(e)}"

# Attempt to load default model on launch
load_status = load_vlm_model(DEFAULT_CHECKPOINT) if os.path.exists(DEFAULT_CHECKPOINT) else "No pre-trained model found. Please upload a checkpoint or train the model."

def generate_radiology_report(input_image, prompt_text, max_new_tokens, temperature):
    """
    Takes an input image and model parameters, processes the image, and outputs a generated medical report.
    """
    global model, tokenizer
    
    if model is None or tokenizer is None:
        return "Model not loaded. Please ensure a valid checkpoint is loaded in the settings."
        
    if input_image is None:
        return "Please upload or select an X-ray image."

    try:
        # Convert image to numpy array
        image = Image.fromarray(input_image.astype('uint8'), 'RGB')
        image_np = np.array(image)
        
        # Apply preprocessing & CLAHE contrast enhancement
        transform = get_transforms(image_size=224, split="val")
        augmented = transform(image=image_np)
        image_tensor = augmented["image"].unsqueeze(0).to(device) # Shape: [1, 3, 224, 224]
        
        # Generate prediction
        generated_outputs = model.generate(
            images=image_tensor,
            tokenizer=tokenizer,
            max_new_tokens=int(max_new_tokens),
            temperature=float(temperature),
            prompt_text=prompt_text
        )
        
        report_text = generated_outputs[0].strip()
        
        # Render a clinically structured layout in markdown
        clinical_markdown = f"""
## 📄 Automated Radiology Interpretation Report

**Clinical Prompt Prefix:** `{prompt_text}`

### 🔍 Technical Observation / Findings
{report_text}

---
*Disclaimer: This report is generated by a Research-Grade Multimodal AI pipeline (VLM) for educational and portfolio demonstration purposes. It is NOT certified for clinical diagnostic use.*
"""
        return clinical_markdown
    except Exception as e:
        return f"An error occurred during report generation: {str(e)}"

# Build Premium Gradio UI
with gr.Blocks(theme=gr.themes.Soft(primary_hue="blue", secondary_hue="slate")) as demo:
    gr.Markdown("""
    # 🏥 Multimodal Chest X-Ray Report Generator
    ### AI-Assisted Radiology Screening & Interpretation Pipeline (Vision-Language Model)
    """)
    
    with gr.Tab("🔬 Inference Pipeline"):
        with gr.Row():
            with gr.Column(scale=1):
                gr.Markdown("### 1. Upload Chest X-Ray")
                input_img = gr.Image(label="X-Ray Scan (DICOM/PNG/JPEG)", type="numpy")
                
                # Parameters Section
                with gr.Accordion("⚙️ Generation Parameters", open=True):
                    prompt_input = gr.Textbox(
                        label="Report Prompt Prefix", 
                        value="Findings: The lungs are", 
                        placeholder="e.g. Findings: The heart is..."
                    )
                    max_tokens = gr.Slider(
                        label="Max New Tokens", 
                        minimum=16, 
                        maximum=128, 
                        value=64, 
                        step=1
                    )
                    temp_slider = gr.Slider(
                        label="Temperature (Creativity/Sampling)", 
                        minimum=0.0, 
                        maximum=1.0, 
                        value=0.7, 
                        step=0.05
                    )
                
                submit_btn = gr.Button("🚀 Generate Radiology Report", variant="primary")
                
            with gr.Column(scale=1.2):
                gr.Markdown("### 2. Clinical Report Output")
                output_report = gr.Markdown(
                    value="*Upload a chest scan on the left and click Generate to see the VLM output.*"
                )

        # Examples
        gr.Markdown("### 💡 Try Example Scans")
        examples_dir = "data/raw/images"
        examples_list = []
        if os.path.exists(examples_dir):
            all_imgs = [os.path.join(examples_dir, f) for f in os.listdir(examples_dir) if f.endswith(('.png', '.jpg', '.jpeg'))]
            examples_list = all_imgs[:3] # Display up to 3 samples

        gr.Examples(
            examples=examples_list if examples_list else [],
            inputs=input_img,
            outputs=output_report
        )

    with gr.Tab("⚙️ Model Settings"):
        gr.Markdown("### Load / Switch Trained Weights")
        with gr.Row():
            ckpt_textbox = gr.Textbox(
                label="Checkpoint Path (.pt)", 
                value=DEFAULT_CHECKPOINT,
                placeholder="Path to model checkpoint, e.g. models/checkpoints/vlm_stage2_best.pt"
            )
            load_btn = gr.Button("🔄 Load Model", variant="secondary")
        
        status_output = gr.Label(value=load_status, label="Model Loading Status")
        
        gr.Markdown("""
        ### Architecture Specs:
        *   **Vision Encoder:** Pre-trained BioViL-T / CheXagent / ViT (spatial patch feature extraction).
        *   **Multimodal Projector:** MLP or Linear cross-modal projection.
        *   **Language Decoder:** Pre-trained BioGPT / Mistral-7B with PEFT LoRA adapter.
        """)

    # Event Handlers
    submit_btn.click(
        fn=generate_radiology_report,
        inputs=[input_img, prompt_input, max_tokens, temp_slider],
        outputs=output_report
    )
    
    load_btn.click(
        fn=load_vlm_model,
        inputs=[ckpt_textbox],
        outputs=status_output
    )

if __name__ == "__main__":
    is_colab = "google.colab" in sys.modules or os.path.exists("/content")
    print(f"Launching Gradio app (Colab detected: {is_colab})")
    demo.launch(server_name="0.0.0.0", server_port=7860, share=is_colab, show_api=False)
